plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '8.3.5'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

application {
    mainClass = 'org.example.Main'
}

repositories {
    mavenCentral()
}

dependencies {

    implementation 'org.postgresql:postgresql:42.7.4'
    implementation('org.mongodb:mongodb-driver-sync:5.1.4')

    implementation 'org.slf4j:slf4j-api:2.0.16'
    implementation 'ch.qos.logback:logback-classic:1.5.7'

    compileOnly("org.projectlombok:lombok:1.18.48")
    annotationProcessor("org.projectlombok:lombok:1.18.48")

    implementation "org.springframework.boot:spring-boot-starter-web:3.5.6"

    compileOnly("org.projectlombok:lombok:1.18.48")
    annotationProcessor("org.projectlombok:lombok:1.18.48")

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
}

shadowJar {
    archiveBaseName.set('gradle_based')
    archiveClassifier.set('all')
    mergeServiceFiles()
}